theme: jekyll-theme-minimal
url: https://acpopa.github.io
title: Andrei-Cătălin Popa
description: Postgraduate Student in Astrophysics and Space Science at Tor Vergata University Rome.
logo: profile.jpg
show_downloads: false
markdown: kramdown