title: "Andrei-Cătălin Popa"
description: "PhD in Astrophysics | Stellar Astrophysics | Binary Stars"
url: "https://acpopa.github.io"
baseurl: ""

author:
  name: "Andrei-Cătălin Popa"
  bio: "PhD Research Student"
  location: "Keele, France"
  employer: "Keele University"
  email: "andrei-catalin.popa AT students.uniroma2.eu"
  github: "acpopa"

markdown: kramdown
kramdown:
  input: GFM
